[package]
name = "matt-parkers-maths-puzzles"
version = "0.1.0"
authors = ["Francis Gagné <fragag1@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
permutohedron = "0.2.4"
structopt = "0.3.13"
